#Eureka
eureka:
  instance:
    instance-id: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discover1:secret1@localhost:8761/eureka


#Gateway
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: create-client
          uri: lb://micro-auth-server
          predicates:
            - Path=/route/authorization-server/create-client
          filters:
            - StripPrefix=1
#            - name: AuthenticationRequestFilter
#              args:
#                message: Request [ ${spring.cloud.gateway.routes[0].uri} ]
#                preLogger: true
#                postLogger: true
        - id: users-service
          uri: lb://micro-users
          predicates:
            - Path=/route/users/**
          filters:
            - StripPrefix=1
            - name: TokenRequestFilter
              args:
                message: Request [ ${spring.cloud.gateway.routes[0].uri} ]
                preLogger: true
                postLogger: true